version: '3.8'

services:
  app:
    build: .
    container_name: line-llm-bot
    restart: always
    ports:
      - "8000:8000"
    volumes:
      - ./data/logs:/app/data/logs
      - ./static:/app/static
      - ./templates:/app/templates
    env_file:
      - .env
    command: sh scripts/deploy.sh
    # depends_on:
    #   - redis

# 可選 Redis 配置
#   redis:
#     image: redis:alpine
#     container_name: line-llm-bot-redis
#     restart: always
#     volumes:
#       - redis-data:/data

# volumes:
#   redis-data:
