version: '3.8'

services:
  app:
    build: .
    container_name: line-llm-bot
    restart: always
    ports:
      - "8000:8000"
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
    env_file:
      - .env
    depends_on:
      - redis

  redis:
    image: redis:alpine
    container_name: line-llm-bot-redis
    restart: always
    volumes:
      - redis-data:/data

volumes:
  redis-data: